trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: Azure Pipelines
  demands:
  - msbuild
  - java

name: '$(version)$(rev:.r)'
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: '4.x'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'src/Client/Client.csproj'
    feedsToUse: 'select'
    vstsFeed: 'f0ee62af-6b8c-4164-8e10-8697924e97f3/c6478b1c-ac51-494d-874d-bf33d7788827'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    Title: 'OpenRP.Framework.Client.net'
    Product: 'Open Roleplay - Client-side Framework'
    Description: 'Open Roleplay - Client-side Framework'
    Company: 'KungRaseri Productions, LLC'
    Copyright: 'Copyright © 2021 - KungRaseri Productions, LLC'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: MSBuild@1
  inputs:
    solution: 'src/Client/Client.csproj'
    msbuildArchitecture: 'x64'
    clean: true
    maximumCpuCount: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/Server/Server.csproj'
    feedsToUse: 'select'
    vstsFeed: 'f0ee62af-6b8c-4164-8e10-8697924e97f3/c6478b1c-ac51-494d-874d-bf33d7788827'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Server/Server.csproj'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'src/UI'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'src/UI'
    customCommand: 'build'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'src/Loadscreen'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'src/Loadscreen'
    customCommand: 'build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'redacted-gaming'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'openrp-framework-ui'
    cliProjectName: 'OpenRP Framework UI'
    cliProjectVersion: '$(Build.BuildNumber)'
    cliSources: 'src/UI'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      sonar.projectVersion=$(version)$(rev:.r)
      sonar.exclusions=src/UI/node_modules/**/*,src/UI/openrp-client-ui/**/*
      sonar.tests=src/UI/tests

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'redacted-gaming'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'openrp-loadscreen'
    cliProjectName: 'OpenRP Loadscreen'
    cliProjectVersion: '$(Build.BuildNumber)'
    cliSources: 'src/Loadscreen'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      sonar.projectVersion=$(version)$(rev:.r)
      sonar.exclusions=src/Loadscreen/node_modules/**/*,src/Loadscreen/openrp-loadscreen-ui/**/*
      sonar.tests=src/Loadscreen/tests

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'redacted-gaming'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'openrp-framework'
    cliProjectName: 'OpenRP Framework'
    cliProjectVersion: '$(Build.BuildNumber)'
    cliSources: 'src/'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      sonar.projectVersion=$(version)$(rev:.r)
      sonar.exclusions=src/Loadscreen/**/*,src/UI/**/*
      sonar.tests=tests/

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: PowerShell@2
  displayName: 'Compile server-data'
  inputs:
    targetType: filePath
    filePath: ./postbuild.ps1

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: 'server-data'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: succeededOrFailed()
