trigger:
- main

pool:
  vmImage: 'vs2017-win2016'
  name: Azure Pipelines
  demands:
  - msbuild
  - java

name: '$(version)$(rev:.r)'
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: '4.x'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'src/Client/Client.csproj'
    feedsToUse: 'select'
    vstsFeed: 'f0ee62af-6b8c-4164-8e10-8697924e97f3/c6478b1c-ac51-494d-874d-bf33d7788827'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs

      **\AssemblyInfo.vb
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    Title: 'OpenRP.Framework.Client.net'
    Product: 'Open Roleplay - Client-side Framework'
    Description: 'Open Roleplay - Client-side Framework'
    Company: 'KungRaseri Productions, LLC'
    Copyright: 'Copyright © 2021 - KungRaseri Productions, LLC'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: MSBuild@1
  inputs:
    solution: 'src/Client/Client.csproj'
    msbuildArchitecture: 'x64'
    clean: true
    maximumCpuCount: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/Server/Server.csproj'
    feedsToUse: 'select'
    vstsFeed: 'f0ee62af-6b8c-4164-8e10-8697924e97f3/c6478b1c-ac51-494d-874d-bf33d7788827'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Server/Server.csproj'

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: sonarcloud
    organization: 'redacted-gaming'
    scannerMode: CLI
    extraProperties: |
     # Additional properties that will be passed to the scanner, 
     # Put one key=value per line, example:
     sonar.projectVersion=$(version)$(rev:.r)
     
- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: PowerShell@2
  displayName: 'Compile server-data'
  inputs:
    targetType: filePath
    filePath: ./postbuild.ps1

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: 'server-data'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: succeededOrFailed()
